### ISSUE TITLE
Bot not detecting lvl 135+ (lvl 120 map) Metins

### ISSUE THREAD

**Issue by Wafend** [SkidBit/Metin-2-Bot-Rubinum2-Pserver#2]
```const int metinIdEnd = 8112;``` (constants.h)

8112 is too low and will only detect metins until Metin of Yang

The vnum list of rubinum can be seen on the wiki http://wiki.rb2.to/monster

Possible fix is to increase it to 8416 which is Legendary Metin of Thunder

https://i.imgur.com/Fe0mAtQ.png

**Comment by SkidBit** [comment]
Thank you very much for this information.
I used an older list for the vnum id's which didn't include the newer metin stones.
I will make sure to include the changes in the newest update.

**Comment by SkidBit** [comment]
I made the necessary changes for the bot to detect all metin stones correcty.
I also added the ore vein id's to be treated as metin stones so those get farmed too if they are present.
Thanks again, will push all the changes and make a new release later this evening/night.

Just as an info: you should not bot without having an eye on your bot accounts in high level because of the ban risk.
